name: pindo_client
description: A Dart wrapper for the Pindo API.
version: 1.0.0
author: Boris Kayi
homepage: https://github.com/silverhairs/pindo_client
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dio: ^4.0.0

dev_dependencies:
  meta: ^1.3.0
  mocktail: ^0.1.4
  test: ^1.16.0
  very_good_analysis: ^2.1.2
