name: pindo_client
description: A Dart package to manage the Pindo API domain.
version: 1.0.0
publish_to: none
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dio: ^4.0.0
  equatable: ^2.0.3
  json_serializable: ^4.1.3
  meta: ^1.3.0

dev_dependencies:
  build_runner: ^2.0.5
  json_annotation: ^4.0.1
  mocktail: ^0.1.4
  test: ^1.16.0
  very_good_analysis: ^2.1.2
